### ISSUE TITLE
Indentation for DO too strict

### ISSUE THREAD

**Issue by scmu** [scmlab/gcl#10]
This code fragment is accepted by the parser:

```
con A, B : Int
var z : Int

{ true }
x, y, z := A, B, 0
{ x * y + z = A * B, bnd: y }
do y /= 0 -> if even y ->
                 x := x * 2
                 y := y / 2
              | odd y  ->
                 z := z + x
                 y := y - 1
             fi
od
{ z = A * B }
```
while this is not:
```
con A, B : Int
var z : Int

{ true }
x, y, z := A, B, 0
{ x * y + z = A * B, bnd: y }
do y /= 0 ->
  if even y ->
      x := x * 2
      y := y / 2
   | odd y  ->
      z := z + x
      y := y - 1
  fi
od
{ z = A * B }
```

It seems that indentation rules for `if` is more permissive --- `x := x *2` is allowed to appear in a new line with less indentation, while that for `do` is too strict --- `if even ...` has to be indented further than `do y /= 0 ->`, even in a new line. 

Ideally I would like both programs to be accepted by the parser.

**Comment by banacorn** [comment]
Token like `do` introduces a "block", which expects an indented block of code (exactly like in Haskell)

```
do line
   line
   line
```

The parser is not happy about the second program, because it now looks like this:

```
do line
  mishap
   line
```

In this case, the indentation level of the "block" starts right at where `y /= 0 ->`

```
do y /= 0 ->
   ^
   3
```

However, the following line `if even y ->` only has the level of `2`

```
do y /= 0 ->
  if even y ->
  ^
  2
```

The program should be accepted by the parser if the following line is indented a bit further like this.

```
do y /= 0 ->
    if even y ->
        x := x * 2
```


> It seems that indentation rules for if is more permissive --- x := x *2 is allowed to appear in a new line with less indentation, while that for do is too strict --- if even ... has to be indented further than do y /= 0 ->, even in a new line.

Tokens like `if` and `do` are treated the same, the following program should also be accepted by the parser.

```
  do even y ->
      x := x * 2
```

Please reopen this issue if you think that tokens like `if` and `do` should not introduce an indented block, and guarded command should be able to be placed freely like this:
```
do 
        | guard -> 
     | guard -> 
          | guard -> 
od 
```
 (not sure if this is feasible)
